Add an alt attribute to all extension thumbnails | Fixes #138
LLK/scratchx pull request #140
Opened 2017-12-30 18:04 UTC by vutondesign

Fixes #138

#### Changes
- Adds an alt attribute to all the extension thumbnails.
- Changes a scratch link to https and fixes two stray ``&``'s.

#### Tests 
I set up an environment to make sure I haven't broken anything, Everything works as expected.

2017-12-31 18:19 UTC, thisandagain requested changes

2017-12-31 18:19 UTC, thisandagain commented on index.html
> +                            <img src="images/extensions/realsense_small.png" alt="ischertechnik robots" />
This should be "Intel RealSense"

2017-12-31 18:20 UTC, thisandagain commented
Looks good @vutondesign. Just one small issue.

2017-12-31 19:53 UTC, vutondesign commented on index.html
> +                            <img src="images/extensions/realsense_small.png" alt="ischertechnik robots" />
Whoops

2017-12-31 19:54 UTC, vutondesign commented
Sorry for the late reply, that should be fixed now. 👍

2018-01-02 15:21 UTC, thisandagain approved these changes

2018-01-02 15:21 UTC, merged

2018-01-02 15:21 UTC, thisandagain commented
Thanks @vutondesign !